### ISSUE TITLE
Support 1.21.1

### ISSUE THREAD

**Issue by CorneliusCornbread** [z3roco01/Inverse-Phantoms#2]
~~Attempting to launch this mod using 1.21.1 Fabric results in the following error~~
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21.1 with version 1.21.
More details:
	 - Mod 'Inverse Phantoms' (inverse_phantoms) v1.1.0+mc1.21 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
~~This can be replicated with *only* this mod and fabric loader 0.16.2 installed~~

Ignore the above, I misread the error and version. Would you be interested in updating the mod for 1.21.1?

**Comment by z3roco01** [comment]
yea, this should be rlly easy actually, ill do it rn

**Comment by z3roco01** [comment]
its fixed with the most recent commit, ill update it on modrinth !

**Comment by z3roco01** [comment]
uploaded here https://modrinth.com/mod/inverse-phantoms/version/WpzUHfTZ !
